name: HusanAI 自动签到
on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  husanai-checkin:
    runs-on: ubuntu-latest
    environment: production
    env:
      PYTHONIOENCODING: utf-8
    steps:
    - uses: actions/checkout@v4

    - uses: astral-sh/setup-uv@v3
      with:
        version: "latest"

    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: 安装依赖
      run: |
        echo "正在安装项目依赖..."
        uv sync
        echo "✅ 环境初始化完成"

    - name: 执行 HusanAI 签到
      env:
        USER_ACCOUNTS: ${{ secrets.USER_ACCOUNTS }}
      run: |
        uv run husanai_checkin.py

    - name: 执行结果
      if: always()
      run: |
        echo "HusanAI 签到任务执行完成"
        echo "时间: $(date)"
